### PR TITLE
WIP feat: Add github actions workflow

### PR DESCRIPTION
**Pull request by rakshith-ravi**

### CODE REVIEW

**Comment by rakshith-ravi** [comment]
@thebongy I've kept this as a base for you to work on top of. Feel free to change my PR's contents.

Also, idk if your `version-check` action supports JSON files for package.json yet

**Comment by thebongy** [comment]
Yup, it supports package.json too, just giving a path to a package.json
file should work

**Comment by thebongy** [comment]
Closed in favor of #8

**Comment by rakshith-ravi** [comment]
#8 targets `feature/npm-publish` branch. Once that gets merged, this PR will be updated, which targets `master`. We can merge this as soon as that gets merged

**Comment by rakshith-ravi** [comment]
@thebongy I've added `NPM_TOKEN` to the secrets. Feel free to merge this once this is done. Make sure master, staging and develop branches are setup as well, along with the appropriate branch protection.

**Pull request merged**
